###########
###########
## load castle trained data, integrate to Seurat object for Vivo and Vitro

wdir <- '/project2/sli68423_1316/projects/U01_aim2/Cross_Expirement/PreProcessing'

source("/project2/sli68423_1316/users/yang/workspace/U01_aim2/scripts/yang/common/funForLoading_PK.R")
source("/project2/sli68423_1316/users/yang/workspace/U01_aim2/scripts/yang/common/data_preparation.R")
source("/project2/sli68423_1316/users/yang/workspace/U01_aim2/scripts/yang/common/castle.R")
source("/project2/sli68423_1316/users/yang/workspace/U01_aim2/scripts/yang/common/Useful_Functions.R")
source("/project2/sli68423_1316/users/yang/workspace/U01_aim2/scripts/yang/common/funForSeurat.R")

min.genes = 200
min.cells = 3
mtpercent = 20
rbpercent = 50
FeatureNum = 2000

opt <- list(
	'inputFiles' = "", #"character", "REQUIRED: 10X dataset paths prepared as hspc.combined object (.RDS generated by prepare_data.R) separated by +",
																													  #'inputFiles'="/projects/li-lab/chenx/2021-U01-CH/CloneTracing_project/data/young/castle/seuratTrainedCt.rds+/projects/li-lab/chenx/2021-U01-CH/CloneTracing_project/data/old/castle/seuratTrainedCt.rds", #"character", "REQUIRED: 10X dataset paths prepared as hspc.combined object (.RDS generated by prepare_data.R) separated by +",
	'outdir' = paste0(wdir, "/Harmony_integration_Cutoff_1K"), #"character", 'Outdir path (default ./)',
	"num_dim_CCA" = 30, #"numeric", "First n dimensions of CCA to use for FindIntegrationAnchors Seurat function (15 by default)",
	"num_dim_weight" = 30, #"numeric", "First n dimensions to use for IntegrateData Seurat function (15 by default)",
	"num_dim" = 30, #"numeric", "First n dimensions of PCA to use for clustering, UMAP and TSNE (15 by default)",
	"num_dim_integrated" = 30, #"numeric", "Number of PCA dimension computed to analyse integrated data (40 by default)",
	"cores" = 1, #"numeric", "Number of cores to use for ordering (for differencially expressed gene between clusters test)",
	### I changed the resolution from 0.25 to 0.3 to produce 15 clusters
	"resolution" = 0.25, #"numeric", "resolution for hspc.combined clustering",
	"correction" = "G2M_score+S_score+G1_score", #"character", "Covariable to use as blocking factor (eg one or several columns of pData: betch, cell cycle phases... separated by +)",
	"logfc_threshold" = 0.25, #"numeric", "logfc threshold for finding cluster markers (1 cluster vs all deg) 0.25 by default",
	"norm_method" = "logNorm", #"character", "normalization method, logNorm (by default) or sctransform",
	"reusePca" = FALSE #"character","re use pca calculated before when caculating anchor weights for each dataset default to FALSE (permit to correct for cell cycle before integration)"
)
opt


#set default arguments values

if (is.null(opt$resolution)) {
	opt$resolution <- 0.5
}

if (is.null(opt$logfc_threshold)) {
	opt$logfc_threshold <- 0.25
}

if (is.null(opt$num_dim_CCA)) {
	opt$num_dim_CCA <- 15
}

if (is.null(opt$num_dim_weight)) {
	opt$num_dim_weight <- 15
}

if (is.null(opt$num_dim)) {
	opt$num_dim <- 15
}

if (is.null(opt$num_dim_integrated)) {
	opt$num_dim_integrated <- 40
}

if (is.null(opt$norm_method)) {
	opt$norm_method <- "logNorm"
}

if (is.null(opt$reusePca)) {
	opt$reusePca <- FALSE
}


print(opt$reusePca)

print(opt$outdir)
dir.create(opt$outdir, recursive = T, showWarnings = F)

corrections <- strsplit(x = opt$correction, split = "\\+")[[1]]


dir.create(opt$outdir, recursive = T, showWarnings = F)


#hspc.listFile <- strsplit(opt$inputFiles,split = "\\+")[[1]]
hspc.listFile <- list.files(path = wdir, pattern = "seuratTrainedCt.rds", recursive = T, full.names = T); hspc.listFile

hspc.list <- list()
#load dataset 

## only the in vito sample
library("Seurat")


################################
################################
################################
# For Vivo data
### remove the first because it is in-vitro
hspc.listFile <- hspc.listFile[-c(1, 4)]
hspc.listFile

# [1] "/project2/sli68423_1316/projects/U01_aim2/Cross_Expirement/PreProcessing/OO/castle/OO_seuratTrainedCt.rds"
# [2] "/project2/sli68423_1316/projects/U01_aim2/Cross_Expirement/PreProcessing/OY/castle/OY_seuratTrainedCt.rds"
# [3] "/project2/sli68423_1316/projects/U01_aim2/Cross_Expirement/PreProcessing/YO/castle/YO_seuratTrainedCt.rds"
# [4] "/project2/sli68423_1316/projects/U01_aim2/Cross_Expirement/PreProcessing/YY/castle/YY_seuratTrainedCt.rds"

for (i in 1:length(x = hspc.listFile)) {
	#i=1
	#For testing, in final workflow sampleName will be incorporated in metadata with the loading of cell ranger matrix
	#sampleName <- strsplit(hspc.listFile[i],split = "/")[[1]][7]; sampleName
	sampleName <- gsub("_seuratTrainedCt.rds", "", basename(hspc.listFile[i])); sampleName
	tmp <- readRDS(hspc.listFile[i])
	#tmp <- subset(tmp, subset =  percentMito < 0.05)
	hspc.list[[i]] <- tmp
	hspc.list[[i]]@meta.data$sampleName <- sampleName
	hspc.list[[i]] <- RenameCells(hspc.list[[i]], add.cell.id = sampleName)

	### Subset cells
	hspc.list[[i]] <- subset(hspc.list[[i]], subset = nFeature_RNA > min.genes)
	range(hspc.list[[i]]@meta.data$nFeature_RNA)

	if (opt$norm_method != "sctransform") {
		hspc.list[[i]] <- NormalizeData(object = hspc.list[[i]], verbose = FALSE)
		hspc.list[[i]] <- FindVariableFeatures(object = hspc.list[[i]], selection.method = "vst",
											   nfeatures = FeatureNum, verbose = FALSE)
	} else {
		hspc.list[[i]] <- SCTransform(hspc.list[[i]], vars.to.regress = corrections, verbose = T)
	}

}
Sampleall.object <- hspc.list
rm(hspc.list)

############### Merge objects
OutputName = "Clonal_HSC"

RUNmerge = "YES"
if (RUNmerge == "YES") {
	FirstObject <- Sampleall.object[[1]]
	RemObject <- Sampleall.object
	RemObject[[1]] <- NULL
	#SCdata.combined <- merge(x = FirstObject, y = RemObject, do.normalize = FALSE, project = "Oocytes_WT")
	#New Command
	SCdata.ALL <- merge(x = FirstObject, y = RemObject, project = "HSC")
	#rm(FirstObject); rm(RemObject)
	#rm(Sampleall.object)

	print(SCdata.ALL)
	CellToUse <- rownames(SCdata.ALL@meta.data[SCdata.ALL@meta.data$nFeature_RNA >= min.genes,]); length(CellToUse)
	head(sort(SCdata.ALL@meta.data$nFeature_RNA), 50)
	SCdata <- subset(SCdata.ALL, cells = CellToUse);
	print(SCdata)
	print(head(SCdata@meta.data))
	head(sort(SCdata@meta.data$nFeature_RNA), 50)

	SCdata.ALL <- SCdata; rm(SCdata)
}


SCdata <- SCdata.ALL
rm(SCdata.ALL)
library("ggpubr")

# graphics.off()
# pdf(paste0(lnWD,"/tableOfCells.pdf"))
# ggtexttable(data.frame(table(SCdata$sampleName)), theme = ttheme("mViolet"))
# dev.off()

# graphics.off()
# pdf(paste0(lnWD,"/qualityAll.pdf"),height = 12)
#  VlnPlot(SCdata, features = c("nFeature_RNA", "percent.mt","percent.rb"), pt.size = 0, ncol = 1, group.by = "sampleName", cols = ClusPalette)
# # VlnPlot(hspc.combined, features = c("nFeature_RNA", "percent.mt","percent.rb"), pt.size = 0, ncol = 1, group.by = "sampleName", cols = c("grey40","grey60","grey80","peachpuff3","peachpuff2","peachpuff"))
# dev.off()
# Save Object
saveRDS(SCdata, file = paste0(opt$outdir, "/cross_vivo_combined_Temp.rds"))
##################
#############


#### run harmony for batch correction

SCdata_original <- SCdata
SCdata <- SCdata_original

ColNamesToPlot = c("seurat_clusters", "sampleName", "predicted")
ColPaletteToPlot = list(ClusPalette, Dark.Pallette, OtherPalette)
IdentToBatchCorrect = "sampleName"

ThetaToBatchCorrect = 1
ChosenPCA = 30
ChosenRes = 0.8

print(paste0("Final Theta: ", IdentToBatchCorrect, ", Final PCA: ", ChosenPCA, ", Final ClusRes: ", ChosenRes))
THETAinpdf = paste(ThetaToBatchCorrect, collapse = '_')

SCdata$sampleName <- as.factor(SCdata$sampleName)
SCdata <- JoinLayers(object = SCdata, layers = NULL)

print("Running PCA")
SCdata <- RunPCA(object = SCdata, npcs = ChosenPCA, verbose = FALSE)
print("Running Harmony")
library("harmony")

SCdata <- harmony::RunHarmony(SCdata, group.by.vars = IdentToBatchCorrect, theta = ThetaToBatchCorrect, project.dim = F)

print("Running UMAP")

SCdata <- RunUMAP(SCdata, reduction = "harmony", dims = 1:ChosenPCA)

print("Running FindNeighbors")
SCdata <- FindNeighbors(SCdata, reduction = "harmony", dims = 1:ChosenPCA)
print("Running FindClusters")
SCdata <- FindClusters(SCdata, resolution = ChosenRes)
print("Completed")

DimPlot(SCdata, group.by = "Library")

saveRDS(SCdata, paste0(opt$outdir, "/cross_vivo_combined.rds"))


################################
################################
################################
##### now work on the single in-vitro sample
hspc.listFile <- list.files(path = wdir, pattern = "seuratTrainedCt.rds", recursive = T, full.names = T); hspc.listFile

hspc.list <- list()
#load dataset 

### consider the first because it is in-vitro
hspc.listFile <- hspc.listFile[c(1, 4)]
for (i in 1:length(x = hspc.listFile)) {
	#i=1
	#For testing, in final workflow sampleName will be incorporated in metadata with the loading of cell ranger matrix
	#sampleName <- strsplit(hspc.listFile[i],split = "/")[[1]][7]; sampleName
	sampleName <- gsub("_seuratTrainedCt.rds", "", basename(hspc.listFile[i])); sampleName
	tmp <- readRDS(hspc.listFile[i])
	#tmp <- subset(tmp, subset =  percentMito < 0.05)
	hspc.list[[i]] <- tmp
	hspc.list[[i]]@meta.data$sampleName <- sampleName
	hspc.list[[i]] <- RenameCells(hspc.list[[i]], add.cell.id = sampleName)

	### Subset cells
	hspc.list[[i]] <- subset(hspc.list[[i]], subset = nFeature_RNA > min.genes)
	range(hspc.list[[i]]@meta.data$nFeature_RNA)

	if (opt$norm_method != "sctransform") {
		hspc.list[[i]] <- NormalizeData(object = hspc.list[[i]], verbose = FALSE)
		hspc.list[[i]] <- FindVariableFeatures(object = hspc.list[[i]], selection.method = "vst",
											   nfeatures = FeatureNum, verbose = FALSE)
	} else {
		hspc.list[[i]] <- SCTransform(hspc.list[[i]], vars.to.regress = corrections, verbose = T)
	}

}
Sampleall.object <- hspc.list
rm(hspc.list)

############### Merge objects
OutputName = "Clonal_HSC"

RUNmerge = "YES"
if (RUNmerge == "YES") {
	FirstObject <- Sampleall.object[[1]]
	RemObject <- Sampleall.object
	RemObject[[1]] <- NULL
	#SCdata.combined <- merge(x = FirstObject, y = RemObject, do.normalize = FALSE, project = "Oocytes_WT")
	#New Command
	SCdata.ALL <- merge(x = FirstObject, y = RemObject, project = "HSC")
	#rm(FirstObject); rm(RemObject)
	#rm(Sampleall.object)

	print(SCdata.ALL)
	CellToUse <- rownames(SCdata.ALL@meta.data[SCdata.ALL@meta.data$nFeature_RNA >= min.genes,]); length(CellToUse)
	head(sort(SCdata.ALL@meta.data$nFeature_RNA), 50)
	SCdata <- subset(SCdata.ALL, cells = CellToUse);
	print(SCdata)
	print(head(SCdata@meta.data))
	head(sort(SCdata@meta.data$nFeature_RNA), 50)

	SCdata.ALL <- SCdata; rm(SCdata)
}


SCdata <- SCdata.ALL
rm(SCdata.ALL)
library("ggpubr")

# graphics.off()
# pdf(paste0(lnWD,"/tableOfCells.pdf"))
# ggtexttable(data.frame(table(SCdata$sampleName)), theme = ttheme("mViolet"))
# dev.off()

# graphics.off()
# pdf(paste0(lnWD,"/qualityAll.pdf"),height = 12)
#  VlnPlot(SCdata, features = c("nFeature_RNA", "percent.mt","percent.rb"), pt.size = 0, ncol = 1, group.by = "sampleName", cols = ClusPalette)
# # VlnPlot(hspc.combined, features = c("nFeature_RNA", "percent.mt","percent.rb"), pt.size = 0, ncol = 1, group.by = "sampleName", cols = c("grey40","grey60","grey80","peachpuff3","peachpuff2","peachpuff"))
# dev.off()
# Save Object
saveRDS(SCdata, file = paste0(opt$outdir, "/cross_vitro_combined_Temp.rds"))
##################
#############


#### run harmony for batch correction

SCdata_original <- SCdata
SCdata <- SCdata_original

ColNamesToPlot = c("seurat_clusters", "sampleName", "predicted")
ColPaletteToPlot = list(ClusPalette, Dark.Pallette, OtherPalette)
IdentToBatchCorrect = "sampleName"

ChosenPCA = 100
ChosenRes = 0.8

print(paste0("Final Theta: ", IdentToBatchCorrect, ", Final PCA: ", ChosenPCA, ", Final ClusRes: ", ChosenRes))
THETAinpdf = paste(ThetaToBatchCorrect, collapse = '_')

SCdata$sampleName <- as.factor(SCdata$sampleName)
SCdata <- JoinLayers(object = SCdata, layers = NULL)

print("Running PCA")
SCdata <- RunPCA(object = SCdata, npcs = ChosenPCA, verbose = FALSE)
print("Running Harmony")
library("harmony")

SCdata <- harmony::RunHarmony(SCdata, group.by.vars = IdentToBatchCorrect, theta = ThetaToBatchCorrect, project.dim = F)

print("Running UMAP")

SCdata <- RunUMAP(SCdata, reduction = "harmony", dims = 1:ChosenPCA)

print("Running FindNeighbors")
SCdata <- FindNeighbors(SCdata, reduction = "harmony", dims = 1:ChosenPCA)
print("Running FindClusters")
SCdata <- FindClusters(SCdata, resolution = ChosenRes)
print("Completed")


DimPlot(SCdata)

saveRDS(SCdata, paste0(opt$outdir, "/cross_vitro_combined.rds"))
###############################
