#!/usr/bin/env Rscript
rm(list = ls())
library("xgboost")
library("igraph")
library(ggplot2)
library(Seurat)
library(Biobase)
library(SingleCellExperiment)
library(doParallel)
library(foreach)

# Non-essential, use castle to predict cell types

# register cores (use all available or set manually)
registerDoParallel(cores = parallel::detectCores())

opaque <- function(color, opacity, max = 255) {
	rgb(t(col2rgb(color)), alpha = opacity, max = max)
}


wdir <- 'projects/U01_aim2/Cross_Expirement/PreProcessing'

source("scripts/common/funForLoading_PK.R")
source("scripts/common/data_preparation.R")
source("scripts/common/castle.R")
source("scripts/common/Useful_Functions.R")

SampleList <- c("O_vitro", "OO", "OY", "Y_vitro", "YY", "YO")
Sample <- "O_vitro"
foreach(Sample = SampleList) %dopar% {
	# for (Sample in c("O_vitro", "OO", "OY", "Y_vitro", "YY", "YO")) {
	print(paste0("Processing age: ", Sample))

	setwd(wdir)

	opt = list(
		'sourceRDS' = paste0(wdir, "/RodriguezPreparation/seuratForCastle.rds"), #"character", "REQUIRED: 10X data to trained classifier prepared as Seurat object (.RDS generated by RodriguezAnalysis.R).",
		'targetRDS' = paste0(wdir, "/", Sample, "/Seurat3/SCdata.rds"), #"character", "REQUIRED: 10X data targeted prepared as seurat object (.RDS generated by SeuratCL.R (filtered, normalized)).",
		'targetMonocleRDS' = NULL, #"character", "REQUIRED: 10X data targeted prepared as monocle object (.RDS generated by seuratMonocleOrdering.R).",
		'outdir' = paste0(wdir, "/", Sample, "/castle") #"character", 'Outdir path (default ./)'
	)

	if (is.null(opt$outdir)) {
		opt$outdir = "./"
	}

	dir.create(opt$outdir, recursive = T, showWarnings = F)

	source_seurat <- readRDS(opt$sourceRDS)
	target_seurat <- readRDS(opt$targetRDS)

	seurat <- castleSeurat3(source_seurat, target_seurat, outdir = opt$outdir)

	if (!is.null(opt$targetMonocleRDS)) {
		target_monocle <- readRDS(opt$targetMonocleRDS)
		monocle <- transfertToMonocle(seurat, target_monocle, outdir = opt$outdir)
		saveRDS(monocle, paste0(opt$outdir, "/monocleTrainedCt.rds")) }


	png(paste0(opt$outdir, "/", Sample, "_CellTypeLearnedPropGG.png"))
	pie <- ggplot(seurat@meta.data, aes(x = factor(1), fill = factor(predicted))) + geom_bar(width = 1)
	pie <- pie +
		coord_polar(theta = "y") +
		theme(axis.title.x = element_blank(), axis.title.y = element_blank())
	print(pie)
	dev.off()

	graphics.off()
	pdf(paste0(wdir, "/", Sample, ".pdf"))
	pie(table(seurat@meta.data$predicted), labels = names(table(seurat@meta.data$predicted)), main = paste(paste("predicted prop", Sample)))
	dev.off()

	saveRDS(seurat, paste0(opt$outdir, "/", Sample, "_seuratTrainedCt.rds"))
	# seurat
}
